### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by juliusroeder** [DanielHfnr/Carla-Object-Detection-Dataset#4]
Hi Daniel,
Would you mind putting a license on this? :)
Otherwise the default copyright applies which means [no one may reproduce, distribute, or create derivatives.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license). 
I don't plan to _reproduce, distribute, or create derivatives_ but I would like to use it for my research and cite it in the paper. 
Thank you.
Julius

**Comment by DanielHfnr** [comment]
Hi @juliusroeder,

no worries, I added a license to the repository.

Best,
Daniel
