### ISSUE TITLE
How did the labels where automatically generated using the semantic segmentation?

### ISSUE THREAD

**Issue by ronyshaji** [DanielHfnr/Carla-Object-Detection-Dataset#5]
Hello

Is it possible to share how you did labeling automatically in the CARLA simulator?

**Comment by DanielHfnr** [comment]
Hi, the setup was basicallly the following.

- Let the car drive in autopilot mode in carla and dump the rgb image plus the semantic segmentation image every few seconds.
- Afterwards i had a python script with opencv that searched for certain classes in the semantic segmentation image and searched for the contours
- Create rectangles around these contours and Safe a file with the label format

this created the labels in 80-90% perfectly. The Rest was adapted manually.

Hope this helps. Unfortunately I dont have the script anymore.
